# Simple workflow for deploying static content to GitHub Pages
name: build-blog-actions
run-name: ${{ github.actor }} is running GitHub Actions
on:
  label:
    types:
      - created
  push:
    branches:
      - main
      - 'feat/**'
  page_build:
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v4
      - name: set node version
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: install dependencies
      - run: npm install
      - name: build vitepress to dist
      - run: npm run build
      
